name = "Hugo Myroad"
license = "GPLv2"
licenselink = "https://github.com/bof/hugo-myroad/blob/master/LICENSE.md"
description = "my own hugo theme, inspired by vimux' Mainroad"
homepage = "https://github.com/bof/hugo-myroad/"
tags = [ 'work-in-progress' ]
features = [ 'none' ]
min_version = "0.30.2"

[author]
  name = "Patrick Schaaf"
  homepage = "https://github.com/bof"

# If porting an existing theme
[original]
  name = "Mainroad"
  homepage = "https://github.com/vimux/Mainroad"
  repo = "https://github.com/Vimux/Mainroad.git"
